project:
  name: blog
  organization: tqer39
  repository: blog
  domain: tqer39.dev

aws:
  account_id: "072693953877"
  region: ap-northeast-1

environments:
  prod:
    subdomain: blog
    vercel:
      framework: nextjs
      root_directory: apps/blog
      build_command: pnpm build
      output_directory: .next

tags:
  common:
    Project: blog
    ManagedBy: terraform
    Repository: github.com/tqer39/blog
