project:
  name: blog
  organization: tqer39
  repository: blog
  domain: tqer39.dev

aws:
  account_id: "072693953877"
  region: ap-northeast-1

discord:
  server_id: "1459749087812260012"
  channels:
    - name: blog-notifications
      category: CI/CD
    - name: blog-alerts
      category: CI/CD
  webhooks:
    blog-dev:
      channel: blog-notifications
    blog-prod:
      channel: blog-alerts

environments:
  dev:
    subdomain: blog-dev
    cms_api:
      database_name: blog-cms-dev
      bucket_name: blog-images-dev-v2
      cdn_domain: cdn-dev.tqer39.dev
    vercel:
      framework: nextjs
      root_directory: apps/blog
      build_command: pnpm build
      output_directory: .next
  prod:
    subdomain: blog
    cms_api:
      database_name: blog-cms-prod
      bucket_name: blog-images-prod-v2
    vercel:
      framework: nextjs
      root_directory: apps/blog
      build_command: pnpm build
      output_directory: .next

tags:
  common:
    Project: blog
    ManagedBy: terraform
    Repository: github.com/tqer39/blog
